from setuptools import setup, find_packages

setup(
    name="spacemap",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "opencv-python",
        "pandas",
        "numpy",
        "torch",
        "kornia",
        "scikit-learn",
        "tifffile",
        "matplotlib",
        "numba",
        "scipy",
        "tqdm",
        "nibabel",
        "seaborn",
        "scikit-image",
    ],
    description="Reconstructing atlas-level single-cell 3D tissue maps from serial sections",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/spacemap",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
    ],
    python_requires=">=3.7",
)
